"""initial schema

Revision ID: aeaaab2b73a1
Revises: 
Create Date: 2026-09-30 21:04:53.669773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeaaab2b73a1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_terms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('term', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term')
    )
    op.create_table('bot_settings',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('term', sa.String(length=200), nullable=False),
    sa.Column('store', sa.Enum('SHOPEE', 'MERCADOLIVRE', 'AMAZON', name='store', native_enum=False, length=20), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store', sa.Enum('SHOPEE', 'MERCADOLIVRE', 'AMAZON', name='store', native_enum=False, length=20), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('seller_name', sa.String(length=200), nullable=True),
    sa.Column('seller_rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('sales_count', sa.Integer(), nullable=True),
    sa.Column('commission_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('is_anime_merch', sa.Boolean(), nullable=True),
    sa.Column('franchise', sa.String(length=200), nullable=True),
    sa.Column('product_type', sa.Enum('MANGA', 'FIGURE', 'BLURAY', 'BOX', 'OUTRO', name='producttype', native_enum=False, length=20), nullable=True),
    sa.Column('volume', sa.String(length=50), nullable=True),
    sa.Column('publisher', sa.String(length=200), nullable=True),
    sa.Column('official_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('classified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_products_active_unclassified', 'products', ['is_anime_merch'], unique=False, postgresql_where=sa.text('active = true'))
    op.create_index('ix_products_store_external', 'products', ['store', 'external_id'], unique=True)
    op.create_table('post_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('price_at_post', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reference_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('affiliate_link', sa.Text(), nullable=False),
    sa.Column('sub_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'POSTED', 'FAILED', 'SKIPPED', name='poststatus', native_enum=False, length=20), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post_queue_status_scheduled', 'post_queue', ['status', 'scheduled_for'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_price_history_product_collected', 'price_history', ['product_id', 'collected_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_price_history_product_collected', table_name='price_history')
    op.drop_table('price_history')
    op.drop_index('ix_post_queue_status_scheduled', table_name='post_queue')
    op.drop_table('post_queue')
    op.drop_index('ix_products_store_external', table_name='products')
    op.drop_index('ix_products_active_unclassified', table_name='products', postgresql_where=sa.text('active = true'))
    op.drop_table('products')
    op.drop_table('keywords')
    op.drop_table('bot_settings')
    op.drop_table('blacklist_terms')
    # ### end Alembic commands ###
