"""conversions table

Revision ID: d2b9d3a630b3
Revises: aeaaab2b73a1
Create Date: 2026-10-01 17:44:57.844667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2b9d3a630b3'
down_revision: Union[str, Sequence[str], None] = 'aeaaab2b73a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store', sa.Enum('SHOPEE', 'MERCADOLIVRE', 'AMAZON', name='store', native_enum=False, length=20), nullable=False),
    sa.Column('sub_id', sa.String(length=64), nullable=True),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('commission', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversions_store_order', 'conversions', ['store', 'order_id'], unique=True)
    op.create_index('ix_conversions_sub_id', 'conversions', ['sub_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conversions_sub_id', table_name='conversions')
    op.drop_index('ix_conversions_store_order', table_name='conversions')
    op.drop_table('conversions')
    # ### end Alembic commands ###
